repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: make fmt
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        stages: [pre-push]
